-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE: Updated NULL and NOT NULL columns.Removed autogenerated double quotes for tables and column names and ensured the script meets the need.

CREATE TABLE category (
    category_id varchar(5)   NOT NULL,
    category char(20)   NOT NULL,
    CONSTRAINT pk_category_id PRIMARY KEY (
        category_id
     ),
	CONSTRAINT uk_category_category UNIQUE (
		category)
);

CREATE TABLE subcategory (
    subcategory_id varchar(8)   NOT NULL,
    category char(20)   NOT NULL,
    CONSTRAINT pk_subcategory_id PRIMARY KEY (
        subcategory_id
     ),
    CONSTRAINT uk_subcategory_category UNIQUE (
        category
     )	
);

CREATE TABLE contacts (
    contact_id int8   NOT NULL,
    first_name char(20)   NOT NULL,
    last_name char(20)   NOT NULL,
    email varchar(80) ,
    CONSTRAINT pk_contacts_contact_id PRIMARY KEY (
        contact_id
     )
);

CREATE TABLE campaign (
    cf_id int8   NOT NULL,
    contact_id int8   NOT NULL,
    compamy_name char(80)   NOT NULL,
    description char(80),
    goal float8   NOT NULL,
    pledged float8   NOT NULL,
    outcome char(12)   NOT NULL,
    backers_count int8   NOT NULL,
    country char(2)   NOT NULL,
    currency char(3)   NOT NULL,
    launched_date date   NOT NULL,
    end_date date ,
    category_id varchar(5)   NOT NULL,
    subcategory_id varchar(8)   NOT NULL,
    CONSTRAINT pk_campaign_cf_id PRIMARY KEY (
        cf_id
     )
);

ALTER TABLE campaign ADD CONSTRAINT fk_campaign_contact_id FOREIGN KEY(contact_id)
REFERENCES contacts (contact_id);

ALTER TABLE campaign ADD CONSTRAINT fk_campaign_category_id FOREIGN KEY(category_id)
REFERENCES category (category_id);

ALTER TABLE campaign ADD CONSTRAINT fk_campaign_subcategory_id FOREIGN KEY(subcategory_id)
REFERENCES subcategory (subcategory_id);

